# Generated by Django 6.0.2 on 2026-04-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_login',
            field=models.BooleanField(default=True, verbose_name='2FA activado para login'),
        ),
    ]
