# Generated by Django 6.0.2 on 2026-05-05 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_bio_user_instagram_url_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Ingresa un enlace de perfil de Facebook válido.', regex='^https?:\\/\\/(www\\.)?facebook\\.com\\/[a-zA-Z0-9.]+\\/?$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Ingresa un enlace de usuario o artista de Spotify válido. No se permiten links a canciones o playlists.', regex='^https?:\\/\\/open\\.spotify\\.com\\/(user|artist)\\/[a-zA-Z0-9]+\\/?(\\?.*)?$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Ingresa un enlace de perfil de TikTok válido. Debe incluir el "@" (ej. https://tiktok.com/@usuario).', regex='^https?:\\/\\/(www\\.)?tiktok\\.com\\/@[a-zA-Z0-9_.]+\\/?$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Ingresa un canal de YouTube válido (ej. https://youtube.com/@canal). No se permiten links a videos.', regex='^https?:\\/\\/(www\\.)?youtube\\.com\\/(c\\/|channel\\/|@)[a-zA-Z0-9_-]+\\/?$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Ingresa un enlace de perfil válido (ej. https://instagram.com/usuario). No se permiten links a fotos/reels.', regex='^https?:\\/\\/(www\\.)?instagram\\.com\\/[a-zA-Z0-9_.]+\\/?$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='x_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Ingresa un enlace de perfil de X/Twitter válido (ej. https://x.com/usuario). No se permiten links a tweets.', regex='^https?:\\/\\/(www\\.)?(twitter\\.com|x\\.com)\\/[a-zA-Z0-9_]+\\/?$')]),
        ),
    ]
