# Generated by Django 6.0.2 on 2026-05-06 03:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_facebook_url_user_spotify_url_user_tiktok_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spotify_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Ingresa un enlace de usuario o artista de Spotify válido. No se permiten links a canciones o playlists.', regex='^https?:\\/\\/open\\.spotify\\.com\\/(intl-[a-zA-Z]{2}\\/)?(user|artist)\\/[a-zA-Z0-9]+\\/?(\\?.*)?$')]),
        ),
    ]
