# Generated by Django 6.0.2 on 2026-05-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_spotify_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_viewed_requests',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última vez que vio solicitudes'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_viewed_suggestions',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última vez que vio sugerencias'),
        ),
    ]
