# Generated by Django 6.0.2 on 2026-05-12 00:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_facebook_url_alter_user_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Ingresa un enlace de perfil de Facebook válido o un enlace compartido.', regex='^https?:\\/\\/(www\\.)?facebook\\.com\\/(share\\/)?[a-zA-Z0-9.]+\\/?(\\?.*)?$')]),
        ),
    ]
