# Generated by Django 6.0.2 on 2026-03-22 22:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Artista')),
                ('spotify_url', models.URLField(unique=True, validators=[django.core.validators.RegexValidator(message='El enlace debe ser una URL válida de Spotify.', regex='^https:\\/\\/(open\\.spotify\\.com|play\\.spotify\\.com)\\/.*$')], verbose_name='Enlace de Spotify')),
                ('user_musician', models.OneToOneField(blank=True, limit_choices_to={'is_musician': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Álbum')),
                ('spotify_url', models.URLField(unique=True, validators=[django.core.validators.RegexValidator(message='El enlace debe ser una URL válida de Spotify.', regex='^https:\\/\\/(open\\.spotify\\.com|play\\.spotify\\.com)\\/.*$')])),
                ('author_notes', models.TextField(blank=True, null=True, verbose_name='Notas del autor (Solo Músicos)')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artist')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=255, verbose_name='Lugar/Recinto')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('date', models.DateField(verbose_name='Fecha del Concierto')),
                ('experience', models.TextField(verbose_name='Reseña de la experiencia')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='concert_photos/', verbose_name='Evidencia Fotográfica')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concert_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Noticia / Actualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('musician', models.ForeignKey(limit_choices_to={'is_musician': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Canción')),
                ('spotify_url', models.URLField(unique=True, validators=[django.core.validators.RegexValidator(message='El enlace debe ser una URL válida de Spotify.', regex='^https:\\/\\/(open\\.spotify\\.com|play\\.spotify\\.com)\\/.*$')])),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Estrellas (0-5)')),
                ('text', models.TextField(verbose_name='Reseña')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.album')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción/Reseña')),
                ('is_official', models.BooleanField(default=False, verbose_name='Es lista oficial del artista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(related_name='playlists', to='music.song')),
            ],
        ),
        migrations.CreateModel(
            name='IdealConcert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('dream_venue', models.CharField(max_length=255, verbose_name='Venue Soñado')),
                ('main_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideal_concerts', to=settings.AUTH_USER_MODEL)),
                ('setlist', models.ManyToManyField(related_name='ideal_concerts', to='music.song')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingConcert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('venue', models.CharField(max_length=255, verbose_name='Lugar')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('musician', models.ForeignKey(limit_choices_to={'is_musician': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
