# Generated by Django 6.0.2 on 2026-04-04 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='entity_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='entity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='spotify_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='El enlace debe ser una URL válida de Spotify.', regex='^https:\\/\\/(open\\.spotify\\.com|play\\.spotify\\.com)\\/.*$')]),
        ),
    ]
