# Generated by Django 6.0.2 on 2026-04-10 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_comment_parent_commentreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertlog',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='concertlog',
            name='city',
        ),
        migrations.RemoveField(
            model_name='concertlog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='concertlog',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='concertlog',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='concertlog',
            name='venue',
        ),
        migrations.AddField(
            model_name='concertlog',
            name='artista',
            field=models.CharField(default='Desconocido', help_text='Nombre del artista principal', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concertlog',
            name='ciudad',
            field=models.CharField(default='desconocida', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concertlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concertlog',
            name='enlace_spotify',
            field=models.URLField(default='desconocido', help_text='Enlace de Spotify del artista para validación', max_length=500, validators=[django.core.validators.RegexValidator(message='El enlace debe ser una URL válida de Spotify.', regex='^https:\\/\\/(open\\.spotify\\.com|play\\.spotify\\.com)\\/.*$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concertlog',
            name='fecha_concierto',
            field=models.DateField(default='2026-01-01', help_text='¿Cuándo fue el evento?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concertlog',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Evidencia fotográfica (Opcional)', null=True, upload_to='conciertos/'),
        ),
        migrations.AddField(
            model_name='concertlog',
            name='lugar',
            field=models.CharField(default='desconocido', help_text='Nombre del recinto (Venue)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concertlog',
            name='resena',
            field=models.TextField(default='desconocido', help_text='Reseña de tu experiencia'),
            preserve_default=False,
        ),
    ]
