# Generated by Django 6.0.2 on 2026-04-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_reaction_unique_together_comment_concert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertlog',
            name='imagen_artista',
            field=models.URLField(blank=True, help_text='Foto oficial del artista desde Spotify', max_length=500, null=True),
        ),
    ]
