# Generated by Django 6.0.2 on 2026-04-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_concertlog_imagen_artista'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertlog',
            name='estado',
            field=models.CharField(default='Desconocido', help_text='Estado o Provincia', max_length=255),
        ),
        migrations.AddField(
            model_name='concertlog',
            name='pais',
            field=models.CharField(default='Desconocido', help_text='País del evento', max_length=255),
        ),
    ]
