# Generated by Django 6.0.2 on 2026-04-11 19:55

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_concertlog_estado_concertlog_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertlog',
            name='fecha_concierto',
            field=models.DateField(help_text='¿Cuándo fue el evento?', validators=[music.models.validar_fecha_no_futura]),
        ),
    ]
