# Generated by Django 6.0.2 on 2026-04-11 20:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_concertlog_fecha_concierto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idealconcert',
            name='country',
        ),
        migrations.RemoveField(
            model_name='idealconcert',
            name='dream_venue',
        ),
        migrations.RemoveField(
            model_name='idealconcert',
            name='main_artist',
        ),
        migrations.RemoveField(
            model_name='idealconcert',
            name='state',
        ),
        migrations.AddField(
            model_name='comment',
            name='ideal_concert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.idealconcert'),
        ),
        migrations.AddField(
            model_name='idealconcert',
            name='artista',
            field=models.CharField(default='Artista Desconocido', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idealconcert',
            name='ciudad',
            field=models.CharField(default='Desconocida', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idealconcert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idealconcert',
            name='enlace_spotify',
            field=models.URLField(default='https://open.spotify.com/artist/123', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idealconcert',
            name='estado',
            field=models.CharField(default='Desconocido', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idealconcert',
            name='imagen_artista',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='idealconcert',
            name='lugar',
            field=models.CharField(default='Desconocido', help_text='El Venue de tus sueños', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idealconcert',
            name='pais',
            field=models.CharField(default='Desconocido', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reaction',
            name='ideal_concert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='music.idealconcert'),
        ),
        migrations.RemoveField(
            model_name='idealconcert',
            name='setlist',
        ),
        migrations.AddField(
            model_name='idealconcert',
            name='setlist',
            field=models.TextField(default='[]', help_text='Lista de canciones en formato JSON'),
            preserve_default=False,
        ),
    ]
