# Generated by Django 6.0.2 on 2026-04-12 04:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_remove_idealconcert_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='is_official',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='title',
        ),
        migrations.AddField(
            model_name='comment',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.playlist'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='canciones',
            field=models.TextField(default=django.utils.timezone.now, help_text='Lista de canciones en formato JSON'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='playlists/', verbose_name='Portada (Opcional)'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='resena',
            field=models.TextField(default='sin resena', verbose_name='¿De qué trata esta playlist?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='titulo',
            field=models.CharField(default='sin titulo', max_length=255, verbose_name='Título de la Playlist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reaction',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='music.playlist'),
        ),
    ]
