# Generated by Django 6.0.2 on 2026-04-12 19:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_remove_playlist_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingconcert',
            name='city',
        ),
        migrations.RemoveField(
            model_name='upcomingconcert',
            name='date',
        ),
        migrations.RemoveField(
            model_name='upcomingconcert',
            name='musician',
        ),
        migrations.RemoveField(
            model_name='upcomingconcert',
            name='venue',
        ),
        migrations.AddField(
            model_name='comment',
            name='upcoming_concert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.upcomingconcert'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='upcoming_concert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='music.upcomingconcert'),
        ),
        migrations.AddField(
            model_name='upcomingconcert',
            name='ciudad',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingconcert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingconcert',
            name='estado',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingconcert',
            name='fecha',
            field=models.DateField(default='2026-01-01', verbose_name='Fecha del Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingconcert',
            name='link_boletos',
            field=models.URLField(blank=True, null=True, verbose_name='Link para comprar boletos (Opcional)'),
        ),
        migrations.AddField(
            model_name='upcomingconcert',
            name='lugar',
            field=models.CharField(default='Desconocido', max_length=255, verbose_name='Venue / Lugar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingconcert',
            name='nombre_tour',
            field=models.CharField(default='Desconocido', max_length=255, verbose_name='Nombre del Tour o Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingconcert',
            name='pais',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingconcert',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_concerts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Aviso')),
                ('mensaje', models.TextField(verbose_name='Mensaje oficial para tus fans')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='Imagen adjunta (Opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.announcement'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='music.announcement'),
        ),
    ]
