# Generated by Django 6.0.2 on 2026-04-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_remove_upcomingconcert_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticeBoard',
        ),
    ]
