# Generated by Django 6.0.2 on 2026-04-26 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_album_created_at_album_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.album'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='music.album'),
        ),
    ]
